# Generated by Django 2.2.6 on 2019-11-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='surname',
            field=models.CharField(default='apellido', max_length=60),
        ),
    ]
