# Generated by Django 2.2.6 on 2019-11-02 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_api', '0002_professor_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='surname',
            field=models.CharField(max_length=60),
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('cursoAnterior', models.OneToOneField(null=True, on_delete='null', to='school_api.Curso')),
            ],
        ),
    ]
