# Generated by Django 2.2.6 on 2019-11-02 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_api', '0003_auto_20191102_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('lastCourse', models.OneToOneField(null=True, on_delete='null', to='school_api.Course')),
            ],
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
