# Generated by Django 2.2.6 on 2019-11-02 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_api', '0005_auto_20191102_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='previousCourse',
            field=models.OneToOneField(blank=True, null=True, on_delete='null', to='school_api.Course'),
        ),
    ]
