# Generated by Django 2.2.6 on 2019-11-02 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_api', '0006_auto_20191102_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('course', models.ForeignKey(on_delete='null', to='school_api.Course')),
                ('previousLesson', models.OneToOneField(blank=True, null=True, on_delete='null', to='school_api.Lesson')),
            ],
        ),
    ]
