# Generated by Django 2.2.6 on 2019-11-03 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_api', '0007_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=60)),
                ('lesson', models.ForeignKey(on_delete='null', to='school_api.Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=60)),
                ('isCorrect', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete='null', to='school_api.Question')),
            ],
        ),
    ]
